### ISSUE TITLE
tensorflow-gpu 1.15.4 no longer on colab / Pypi

### ISSUE THREAD

**Issue by grandjeanlab** [yu02019/BEN#4]
Hi, 
I'be been trying to use BEN, but I can't get to try the  collab notebook because the TF dependency no longer exists on collab, but also not on Pypi, even for older python versions (e.g. 3.7)

Do you still have a linux-based installation that works ? If so, I should be able to build a container out of it to make do.

**Comment by yu02019** [comment]
Thank you for bringing this to our attention. I guess other 1.15 series (e.g., 1.15.1) could also work for BEN.

Regarding the unavailability of TensorFlow on Colab and PyPI, it appears to be related to the compatibility issues with the newer NVIDIA GPUs (RTX30 series) that only support CUDA 11.0 and higher. Many projects based on Tensorflow 1.xx still require CUDA 10.x or older versions, which might be causing the problem. However, NVIDIA has maintained an official version of TensorFlow 1.15 that you can access [here](https://github.com/NVIDIA/tensorflow/releases). You can follow the instructions on this page to install TensorFlow 1.15 using pip command.

I test this installation on my Ubuntu server and it works well. I hope this could address your issue.
